name: Deploy to Docker

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//\-/g')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/p247beserver:${{ env.BRANCH_NAME }}

      - name: Deploy to Docker
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            CURRENT_BRANCH="${{ github.ref }}"
            CURRENT_BRANCH=${CURRENT_BRANCH#refs/heads/}

            REPOSITORY_NAME="${{ secrets.REPOSITORY_NAME }}"

            if [ -d "$REPOSITORY_NAME" ]; then
              cd $REPOSITORY_NAME
              git checkout $CURRENT_BRANCH
              git pull
            else
              git clone https://github.com/jspawar80/$REPOSITORY_NAME.git
              cd $REPOSITORY_NAME
              git checkout $CURRENT_BRANCH
            fi
            sed -e "s/branchname/${{ env.BRANCH_NAME }}/g" docker-compose-template.yml > docker-compose.yml
            docker-compose down
            docker-compose pull
            docker-compose up -d
